@countries[{"name" => "	Afghanistan	", "continent" => "	Asia	"},
{"name" => "	Åland Islands	", "continent" => "	Europe	"},
{"name" => "	Albania	", "continent" => "	Europe	"},
{"name" => "	Algeria	", "continent" => "	Africa	"},
{"name" => "	American Samoa	", "continent" => "	Oceania	"},
{"name" => "	Andorra	", "continent" => "	Europe	"},
{"name" => "	Angola	", "continent" => "	Africa	"},
{"name" => "	Anguilla	", "continent" => "	North America	"},
{"name" => "	Antarctica	", "continent" => "	Antarctica	"},
{"name" => "	Antigua and Barbuda	", "continent" => "	North America	"},
{"name" => "	Argentina	", "continent" => "	South America	"},
{"name" => "	Armenia	", "continent" => "	Asia	"},
{"name" => "	Aruba	", "continent" => "	North America	"},
{"name" => "	Australia	", "continent" => "	Oceania	"},
{"name" => "	Austria	", "continent" => "	Europe	"},
{"name" => "	Azerbaijan	", "continent" => "	Asia	"},
{"name" => "	Bahamas	", "continent" => "	North America	"},
{"name" => "	Bahrain	", "continent" => "	Asia	"},
{"name" => "	Bangladesh	", "continent" => "	Asia	"},
{"name" => "	Barbados	", "continent" => "	North America	"},
{"name" => "	Belarus	", "continent" => "	Europe	"},
{"name" => "	Belgium	", "continent" => "	Europe	"},
{"name" => "	Belize	", "continent" => "	North America	"},
{"name" => "	Benin	", "continent" => "	Africa	"},
{"name" => "	Bermuda	", "continent" => "	North America	"},
{"name" => "	Bhutan	", "continent" => "	Asia	"},
{"name" => "	Bolivia (Plurinational State of)	", "continent" => "	South America	"},
{"name" => "	Bonaire, Sint Eustatius and Saba	", "continent" => "	North America	"},
{"name" => "	Bosnia and Herzegovina	", "continent" => "	Europe	"},
{"name" => "	Botswana	", "continent" => "	Africa	"},
{"name" => "	Bouvet Island	", "continent" => "	South America	"},
{"name" => "	Brazil	", "continent" => "	South America	"},
{"name" => "	British Indian Ocean Territory	", "continent" => "	Africa	"},
{"name" => "	British Virgin Islands	", "continent" => "	North America	"},
{"name" => "	Brunei Darussalam	", "continent" => "	Asia	"},
{"name" => "	Bulgaria	", "continent" => "	Europe	"},
{"name" => "	Burkina Faso	", "continent" => "	Africa	"},
{"name" => "	Burundi	", "continent" => "	Africa	"},
{"name" => "	Cabo Verde	", "continent" => "	Africa	"},
{"name" => "	Cambodia	", "continent" => "	Asia	"},
{"name" => "	Cameroon	", "continent" => "	Africa	"},
{"name" => "	Canada	", "continent" => "	North America	"},
{"name" => "	Cayman Islands	", "continent" => "	North America	"},
{"name" => "	Central African Republic	", "continent" => "	Africa	"},
{"name" => "	Chad	", "continent" => "	Africa	"},
{"name" => "	Chile	", "continent" => "	South America	"},
{"name" => "	China	", "continent" => "	Asia	"},
{"name" => "	China, Hong Kong Special Administrative Region	", "continent" => "	Asia	"},
{"name" => "	China, Macao Special Administrative Region	", "continent" => "	Asia	"},
{"name" => "	Christmas Island	", "continent" => "	Oceania	"},
{"name" => "	Cocos (Keeling) Islands	", "continent" => "	Oceania	"},
{"name" => "	Colombia	", "continent" => "	South America	"},
{"name" => "	Comoros	", "continent" => "	Africa	"},
{"name" => "	Congo	", "continent" => "	Africa	"},
{"name" => "	Cook Islands	", "continent" => "	Oceania	"},
{"name" => "	Costa Rica	", "continent" => "	North America	"},
{"name" => "	Côte d’Ivoire	", "continent" => "	Africa	"},
{"name" => "	Croatia	", "continent" => "	Europe	"},
{"name" => "	Cuba	", "continent" => "	North America	"},
{"name" => "	Curaçao	", "continent" => "	North America	"},
{"name" => "	Cyprus	", "continent" => "	Asia	"},
{"name" => "	Czechia	", "continent" => "	Europe	"},
{"name" => "	Democratic People's Republic of Korea	", "continent" => "	Asia	"},
{"name" => "	Democratic Republic of the Congo	", "continent" => "	Africa	"},
{"name" => "	Denmark	", "continent" => "	Europe	"},
{"name" => "	Djibouti	", "continent" => "	Africa	"},
{"name" => "	Dominica	", "continent" => "	North America	"},
{"name" => "	Dominican Republic	", "continent" => "	North America	"},
{"name" => "	Ecuador	", "continent" => "	South America	"},
{"name" => "	Egypt	", "continent" => "	Africa	"},
{"name" => "	El Salvador	", "continent" => "	North America	"},
{"name" => "	Equatorial Guinea	", "continent" => "	Africa	"},
{"name" => "	Eritrea	", "continent" => "	Africa	"},
{"name" => "	Estonia	", "continent" => "	Europe	"},
{"name" => "	Eswatini	", "continent" => "	Africa	"},
{"name" => "	Ethiopia	", "continent" => "	Africa	"},
{"name" => "	Falkland Islands (Malvinas)	", "continent" => "	South America	"},
{"name" => "	Faroe Islands	", "continent" => "	Europe	"},
{"name" => "	Fiji	", "continent" => "	Oceania	"},
{"name" => "	Finland	", "continent" => "	Europe	"},
{"name" => "	France	", "continent" => "	Europe	"},
{"name" => "	French Guiana	", "continent" => "	South America	"},
{"name" => "	French Polynesia	", "continent" => "	Oceania	"},
{"name" => "	French Southern Territories	", "continent" => "	Africa	"},
{"name" => "	Gabon	", "continent" => "	Africa	"},
{"name" => "	Gambia	", "continent" => "	Africa	"},
{"name" => "	Georgia	", "continent" => "	Asia	"},
{"name" => "	Germany	", "continent" => "	Europe	"},
{"name" => "	Ghana	", "continent" => "	Africa	"},
{"name" => "	Gibraltar	", "continent" => "	Europe	"},
{"name" => "	Greece	", "continent" => "	Europe	"},
{"name" => "	Greenland	", "continent" => "	North America	"},
{"name" => "	Grenada	", "continent" => "	North America	"},
{"name" => "	Guadeloupe	", "continent" => "	North America	"},
{"name" => "	Guam	", "continent" => "	Oceania	"},
{"name" => "	Guatemala	", "continent" => "	North America	"},
{"name" => "	Guernsey	", "continent" => "	Europe	"},
{"name" => "	Guinea	", "continent" => "	Africa	"},
{"name" => "	Guinea-Bissau	", "continent" => "	Africa	"},
{"name" => "	Guyana	", "continent" => "	South America	"},
{"name" => "	Haiti	", "continent" => "	North America	"},
{"name" => "	Heard Island and McDonald Islands	", "continent" => "	Oceania	"},
{"name" => "	Holy See	", "continent" => "	Europe	"},
{"name" => "	Honduras	", "continent" => "	North America	"},
{"name" => "	Hungary	", "continent" => "	Europe	"},
{"name" => "	Iceland	", "continent" => "	Europe	"},
{"name" => "	India	", "continent" => "	Asia	"},
{"name" => "	Indonesia	", "continent" => "	Asia	"},
{"name" => "	Iran (Islamic Republic of)	", "continent" => "	Asia	"},
{"name" => "	Iraq	", "continent" => "	Asia	"},
{"name" => "	Ireland	", "continent" => "	Europe	"},
{"name" => "	Isle of Man	", "continent" => "	Europe	"},
{"name" => "	Israel	", "continent" => "	Asia	"},
{"name" => "	Italy	", "continent" => "	Europe	"},
{"name" => "	Jamaica	", "continent" => "	North America	"},
{"name" => "	Japan	", "continent" => "	Asia	"},
{"name" => "	Jersey	", "continent" => "	Europe	"},
{"name" => "	Jordan	", "continent" => "	Asia	"},
{"name" => "	Kazakhstan	", "continent" => "	Asia	"},
{"name" => "	Kenya	", "continent" => "	Africa	"},
{"name" => "	Kiribati	", "continent" => "	Oceania	"},
{"name" => "	Kuwait	", "continent" => "	Asia	"},
{"name" => "	Kyrgyzstan	", "continent" => "	Asia	"},
{"name" => "	Lao People's Democratic Republic	", "continent" => "	Asia	"},
{"name" => "	Latvia	", "continent" => "	Europe	"},
{"name" => "	Lebanon	", "continent" => "	Asia	"},
{"name" => "	Lesotho	", "continent" => "	Africa	"},
{"name" => "	Liberia	", "continent" => "	Africa	"},
{"name" => "	Libya	", "continent" => "	Africa	"},
{"name" => "	Liechtenstein	", "continent" => "	Europe	"},
{"name" => "	Lithuania	", "continent" => "	Europe	"},
{"name" => "	Luxembourg	", "continent" => "	Europe	"},
{"name" => "	Madagascar	", "continent" => "	Africa	"},
{"name" => "	Malawi	", "continent" => "	Africa	"},
{"name" => "	Malaysia	", "continent" => "	Asia	"},
{"name" => "	Maldives	", "continent" => "	Asia	"},
{"name" => "	Mali	", "continent" => "	Africa	"},
{"name" => "	Malta	", "continent" => "	Europe	"},
{"name" => "	Marshall Islands	", "continent" => "	Oceania	"},
{"name" => "	Martinique	", "continent" => "	North America	"},
{"name" => "	Mauritania	", "continent" => "	Africa	"},
{"name" => "	Mauritius	", "continent" => "	Africa	"},
{"name" => "	Mayotte	", "continent" => "	Africa	"},
{"name" => "	Mexico	", "continent" => "	North America	"},
{"name" => "	Micronesia (Federated States of)	", "continent" => "	Oceania	"},
{"name" => "	Monaco	", "continent" => "	Europe	"},
{"name" => "	Mongolia	", "continent" => "	Asia	"},
{"name" => "	Montenegro	", "continent" => "	Europe	"},
{"name" => "	Montserrat	", "continent" => "	North America	"},
{"name" => "	Morocco	", "continent" => "	Africa	"},
{"name" => "	Mozambique	", "continent" => "	Africa	"},
{"name" => "	Myanmar	", "continent" => "	Asia	"},
{"name" => "	Namibia	", "continent" => "	Africa	"},
{"name" => "	Nauru	", "continent" => "	Oceania	"},
{"name" => "	Nepal	", "continent" => "	Asia	"},
{"name" => "	Netherlands	", "continent" => "	Europe	"},
{"name" => "	New Caledonia	", "continent" => "	Oceania	"},
{"name" => "	New Zealand	", "continent" => "	Oceania	"},
{"name" => "	Nicaragua	", "continent" => "	North America	"},
{"name" => "	Niger	", "continent" => "	Africa	"},
{"name" => "	Nigeria	", "continent" => "	Africa	"},
{"name" => "	Niue	", "continent" => "	Oceania	"},
{"name" => "	Norfolk Island	", "continent" => "	Oceania	"},
{"name" => "	North Macedonia	", "continent" => "	Europe	"},
{"name" => "	Northern Mariana Islands	", "continent" => "	Oceania	"},
{"name" => "	Norway	", "continent" => "	Europe	"},
{"name" => "	Oman	", "continent" => "	Asia	"},
{"name" => "	Pakistan	", "continent" => "	Asia	"},
{"name" => "	Palau	", "continent" => "	Oceania	"},
{"name" => "	Panama	", "continent" => "	North America	"},
{"name" => "	Papua New Guinea	", "continent" => "	Oceania	"},
{"name" => "	Paraguay	", "continent" => "	South America	"},
{"name" => "	Peru	", "continent" => "	South America	"},
{"name" => "	Philippines	", "continent" => "	Asia	"},
{"name" => "	Pitcairn	", "continent" => "	Oceania	"},
{"name" => "	Poland	", "continent" => "	Europe	"},
{"name" => "	Portugal	", "continent" => "	Europe	"},
{"name" => "	Puerto Rico	", "continent" => "	North America	"},
{"name" => "	Qatar	", "continent" => "	Asia	"},
{"name" => "	Republic of Korea	", "continent" => "	Asia	"},
{"name" => "	Republic of Moldova	", "continent" => "	Europe	"},
{"name" => "	Réunion	", "continent" => "	Africa	"},
{"name" => "	Romania	", "continent" => "	Europe	"},
{"name" => "	Russian Federation	", "continent" => "	Europe	"},
{"name" => "	Rwanda	", "continent" => "	Africa	"},
{"name" => "	Saint Barthélemy	", "continent" => "	North America	"},
{"name" => "	Saint Helena	", "continent" => "	Africa	"},
{"name" => "	Saint Kitts and Nevis	", "continent" => "	North America	"},
{"name" => "	Saint Lucia	", "continent" => "	North America	"},
{"name" => "	Saint Martin (French Part)	", "continent" => "	North America	"},
{"name" => "	Saint Pierre and Miquelon	", "continent" => "	North America	"},
{"name" => "	Saint Vincent and the Grenadines	", "continent" => "	North America	"},
{"name" => "	Samoa	", "continent" => "	Oceania	"},
{"name" => "	San Marino	", "continent" => "	Europe	"},
{"name" => "	Sao Tome and Principe	", "continent" => "	Africa	"},
{"name" => "	Sark	", "continent" => "	Europe	"},
{"name" => "	Saudi Arabia	", "continent" => "	Asia	"},
{"name" => "	Senegal	", "continent" => "	Africa	"},
{"name" => "	Serbia	", "continent" => "	Europe	"},
{"name" => "	Seychelles	", "continent" => "	Africa	"},
{"name" => "	Sierra Leone	", "continent" => "	Africa	"},
{"name" => "	Singapore	", "continent" => "	Asia	"},
{"name" => "	Sint Maarten (Dutch part)	", "continent" => "	North America	"},
{"name" => "	Slovakia	", "continent" => "	Europe	"},
{"name" => "	Slovenia	", "continent" => "	Europe	"},
{"name" => "	Solomon Islands	", "continent" => "	Oceania	"},
{"name" => "	Somalia	", "continent" => "	Africa	"},
{"name" => "	South Africa	", "continent" => "	Africa	"},
{"name" => "	South Georgia and the South Sandwich Islands	", "continent" => "	South America	"},
{"name" => "	South Sudan	", "continent" => "	Africa	"},
{"name" => "	Spain	", "continent" => "	Europe	"},
{"name" => "	Sri Lanka	", "continent" => "	Asia	"},
{"name" => "	State of Palestine	", "continent" => "	Asia	"},
{"name" => "	Sudan	", "continent" => "	Africa	"},
{"name" => "	Suriname	", "continent" => "	South America	"},
{"name" => "	Svalbard and Jan Mayen Islands	", "continent" => "	Europe	"},
{"name" => "	Sweden	", "continent" => "	Europe	"},
{"name" => "	Switzerland	", "continent" => "	Europe	"},
{"name" => "	Syrian Arab Republic	", "continent" => "	Asia	"},
{"name" => "	Tajikistan	", "continent" => "	Asia	"},
{"name" => "	Thailand	", "continent" => "	Asia	"},
{"name" => "	Timor-Leste	", "continent" => "	Asia	"},
{"name" => "	Togo	", "continent" => "	Africa	"},
{"name" => "	Tokelau	", "continent" => "	Oceania	"},
{"name" => "	Tonga	", "continent" => "	Oceania	"},
{"name" => "	Trinidad and Tobago	", "continent" => "	North America	"},
{"name" => "	Tunisia	", "continent" => "	Africa	"},
{"name" => "	Turkey	", "continent" => "	Asia	"},
{"name" => "	Turkmenistan	", "continent" => "	Asia	"},
{"name" => "	Turks and Caicos Islands	", "continent" => "	North America	"},
{"name" => "	Tuvalu	", "continent" => "	Oceania	"},
{"name" => "	Uganda	", "continent" => "	Africa	"},
{"name" => "	Ukraine	", "continent" => "	Europe	"},
{"name" => "	United Arab Emirates	", "continent" => "	Asia	"},
{"name" => "	United Kingdom of Great Britain and Northern Ireland	", "continent" => "	Europe	"},
{"name" => "	United Republic of Tanzania	", "continent" => "	Africa	"},
{"name" => "	United States Minor Outlying Islands	", "continent" => "	Oceania	"},
{"name" => "	United States of America	", "continent" => "	North America	"},
{"name" => "	United States Virgin Islands	", "continent" => "	North America	"},
{"name" => "	Uruguay	", "continent" => "	South America	"},
{"name" => "	Uzbekistan	", "continent" => "	Asia	"},
{"name" => "	Vanuatu	", "continent" => "	Oceania	"},
{"name" => "	Venezuela (Bolivarian Republic of)	", "continent" => "	South America	"},
{"name" => "	Viet Nam	", "continent" => "	Asia	"},
{"name" => "	Wallis and Futuna Islands	", "continent" => "	Oceania	"},
{"name" => "	Western Sahara	", "continent" => "	Africa	"},
{"name" => "	Yemen	", "continent" => "	Asia	"},
{"name" => "	Zambia	", "continent" => "	Africa	"},
{"name" => "	Zimbabwe	", "continent" => "	Africa	"}]
