require_relative( "../models/location.rb" )
require_relative( "../models/country.rb" )
require_relative( "../models/continent.rb" )

Continent.delete_all
Country.delete_all

asia =  Continent.new({"name" => "Asia"})
europe = Continent.new({"name" => "Europe"})
africa = Continent.new({"name" => "Africa"})
north_america = Continent.new({"name" => "North America"})
south_america = Continent.new({"name" => "South America"})
oceania = Continent.new({"name" => "Oceania"})
antarctica = Continent.new({"name" => "Antarctica"})

asia.save()
europe.save()
africa.save()
north_america.save()
south_america.save()
oceania.save()
antarctica.save()

continents = [asia, europe, africa, north_america, south_america, oceania, antarctica]

countries = [
  {"name" => "Afghanistan", "continent" => asia},
  {"name" => "Åland Islands", "continent" => europe},
  {"name" => "Albania", "continent" => europe},
  {"name" => "Algeria", "continent" => africa},
  {"name" => "American Samoa", "continent" => oceania},
  {"name" => "Andorra", "continent" => europe},
  {"name" => "Angola", "continent" => africa},
  {"name" => "Anguilla", "continent" => north_america},
  {"name" => "Antarctica", "continent" => antarctica},
  {"name" => "Antigua and Barbuda", "continent" => north_america},
  {"name" => "Argentina", "continent" => south_america},
  {"name" => "Armenia", "continent" => asia},
  {"name" => "Aruba", "continent" => north_america},
  {"name" => "Australia", "continent" => oceania},
  {"name" => "Austria", "continent" => europe},
  {"name" => "Azerbaijan", "continent" => asia},
  {"name" => "Bahamas", "continent" => north_america},
  {"name" => "Bahrain", "continent" => asia},
  {"name" => "Bangladesh", "continent" => asia},
  {"name" => "Barbados", "continent" => north_america},
  {"name" => "Belarus", "continent" => europe},
  {"name" => "Belgium", "continent" => europe},
  {"name" => "Belize", "continent" => north_america},
  {"name" => "Benin", "continent" => africa},
  {"name" => "Bermuda", "continent" => north_america},
  {"name" => "Bhutan", "continent" => asia},
  {"name" => "Bolivia (Plurinational State of)", "continent" => south_america},
  {"name" => "Bonaire, Sint Eustatius and Saba", "continent" => north_america},
  {"name" => "Bosnia and Herzegovina", "continent" => europe},
  {"name" => "Botswana", "continent" => africa},
  {"name" => "Bouvet Island", "continent" => south_america},
  {"name" => "Brazil", "continent" => south_america},
  {"name" => "British Indian Ocean Territory", "continent" => africa},
  {"name" => "British Virgin Islands", "continent" => north_america},
  {"name" => "Brunei (Brunei Darussalam)", "continent" => asia},
  {"name" => "Bulgaria", "continent" => europe},
  {"name" => "Burkina Faso", "continent" => africa},
  {"name" => "Burundi", "continent" => africa},
  {"name" => "Cabo Verde", "continent" => africa},
  {"name" => "Cambodia", "continent" => asia},
  {"name" => "Cameroon", "continent" => africa},
  {"name" => "Canada", "continent" => north_america},
  {"name" => "Cayman Islands", "continent" => north_america},
  {"name" => "Central African Republic", "continent" => africa},
  {"name" => "Chad", "continent" => africa},
  {"name" => "Chile", "continent" => south_america},
  {"name" => "China", "continent" => asia},
  {"name" => "China, Hong Kong Special Administrative Region", "continent" => asia},
  {"name" => "China, Macao Special Administrative Region", "continent" => asia},
  {"name" => "Christmas Island", "continent" => oceania},
  {"name" => "Cocos (Keeling) Islands", "continent" => oceania},
  {"name" => "Colombia", "continent" => south_america},
  {"name" => "Comoros", "continent" => africa},
  {"name" => "Congo", "continent" => africa},
  {"name" => "Cook Islands", "continent" => oceania},
  {"name" => "Costa Rica", "continent" => north_america},
  {"name" => "Côte d’Ivoire (Ivory Coast)", "continent" => africa},
  {"name" => "Croatia", "continent" => europe},
  {"name" => "Cuba", "continent" => north_america},
  {"name" => "Curaçao", "continent" => north_america},
  {"name" => "Cyprus", "continent" => asia},
  {"name" => "Czechia", "continent" => europe},
  {"name" => "North Korea (Democratic People's Republic of Korea)", "continent" => asia},
  {"name" => "Democratic Republic of the Congo", "continent" => africa},
  {"name" => "Denmark", "continent" => europe},
  {"name" => "Djibouti", "continent" => africa},
  {"name" => "Dominica", "continent" => north_america},
  {"name" => "Dominican Republic", "continent" => north_america},
  {"name" => "Ecuador", "continent" => south_america},
  {"name" => "Egypt", "continent" => africa},
  {"name" => "El Salvador", "continent" => north_america},
  {"name" => "Equatorial Guinea", "continent" => africa},
  {"name" => "Eritrea", "continent" => africa},
  {"name" => "Estonia", "continent" => europe},
  {"name" => "Eswatini", "continent" => africa},
  {"name" => "Ethiopia", "continent" => africa},
  {"name" => "Falkland Islands (Malvinas)", "continent" => south_america},
  {"name" => "Faroe Islands", "continent" => europe},
  {"name" => "Fiji", "continent" => oceania},
  {"name" => "Finland", "continent" => europe},
  {"name" => "France", "continent" => europe},
  {"name" => "French Guiana", "continent" => south_america},
  {"name" => "French Polynesia", "continent" => oceania},
  {"name" => "French Southern Territories", "continent" => africa},
  {"name" => "Gabon", "continent" => africa},
  {"name" => "Gambia", "continent" => africa},
  {"name" => "Georgia", "continent" => asia},
  {"name" => "Germany", "continent" => europe},
  {"name" => "Ghana", "continent" => africa},
  {"name" => "Gibraltar", "continent" => europe},
  {"name" => "Greece", "continent" => europe},
  {"name" => "Greenland", "continent" => north_america},
  {"name" => "Grenada", "continent" => north_america},
  {"name" => "Guadeloupe", "continent" => north_america},
  {"name" => "Guam", "continent" => oceania},
  {"name" => "Guatemala", "continent" => north_america},
  {"name" => "Guernsey", "continent" => europe},
  {"name" => "Guinea", "continent" => africa},
  {"name" => "Guinea-Bissau", "continent" => africa},
  {"name" => "Guyana", "continent" => south_america},
  {"name" => "Haiti", "continent" => north_america},
  {"name" => "Heard Island and McDonald Islands", "continent" => oceania},
  {"name" => "Vatican City (Holy See)", "continent" => europe},
  {"name" => "Honduras", "continent" => north_america},
  {"name" => "Hungary", "continent" => europe},
  {"name" => "Iceland", "continent" => europe},
  {"name" => "India", "continent" => asia},
  {"name" => "Indonesia", "continent" => asia},
  {"name" => "Iran (Islamic Republic of)", "continent" => asia},
  {"name" => "Iraq", "continent" => asia},
  {"name" => "Ireland", "continent" => europe},
  {"name" => "Isle of Man", "continent" => europe},
  {"name" => "Israel", "continent" => asia},
  {"name" => "Italy", "continent" => europe},
  {"name" => "Jamaica", "continent" => north_america},
  {"name" => "Japan", "continent" => asia},
  {"name" => "Jersey", "continent" => europe},
  {"name" => "Jordan", "continent" => asia},
  {"name" => "Kazakhstan", "continent" => asia},
  {"name" => "Kenya", "continent" => africa},
  {"name" => "Kiribati", "continent" => oceania},
  {"name" => "Kuwait", "continent" => asia},
  {"name" => "Kyrgyzstan", "continent" => asia},
  {"name" => "Laos (Lao People's Democratic Republic)", "continent" => asia},
  {"name" => "Latvia", "continent" => europe},
  {"name" => "Lebanon", "continent" => asia},
  {"name" => "Lesotho", "continent" => africa},
  {"name" => "Liberia", "continent" => africa},
  {"name" => "Libya", "continent" => africa},
  {"name" => "Liechtenstein", "continent" => europe},
  {"name" => "Lithuania", "continent" => europe},
  {"name" => "Luxembourg", "continent" => europe},
  {"name" => "Madagascar", "continent" => africa},
  {"name" => "Malawi", "continent" => africa},
  {"name" => "Malaysia", "continent" => asia},
  {"name" => "Maldives", "continent" => asia},
  {"name" => "Mali", "continent" => africa},
  {"name" => "Malta", "continent" => europe},
  {"name" => "Marshall Islands", "continent" => oceania},
  {"name" => "Martinique", "continent" => north_america},
  {"name" => "Mauritania", "continent" => africa},
  {"name" => "Mauritius", "continent" => africa},
  {"name" => "Mayotte", "continent" => africa},
  {"name" => "Mexico", "continent" => north_america},
  {"name" => "Micronesia (Federated States of)", "continent" => oceania},
  {"name" => "Monaco", "continent" => europe},
  {"name" => "Mongolia", "continent" => asia},
  {"name" => "Montenegro", "continent" => europe},
  {"name" => "Montserrat", "continent" => north_america},
  {"name" => "Morocco", "continent" => africa},
  {"name" => "Mozambique", "continent" => africa},
  {"name" => "Myanmar", "continent" => asia},
  {"name" => "Namibia", "continent" => africa},
  {"name" => "Nauru", "continent" => oceania},
  {"name" => "Nepal", "continent" => asia},
  {"name" => "Netherlands", "continent" => europe},
  {"name" => "New Caledonia", "continent" => oceania},
  {"name" => "New Zealand", "continent" => oceania},
  {"name" => "Nicaragua", "continent" => north_america},
  {"name" => "Niger", "continent" => africa},
  {"name" => "Nigeria", "continent" => africa},
  {"name" => "Niue", "continent" => oceania},
  {"name" => "Norfolk Island", "continent" => oceania},
  {"name" => "North Macedonia", "continent" => europe},
  {"name" => "Northern Mariana Islands", "continent" => oceania},
  {"name" => "Norway", "continent" => europe},
  {"name" => "Oman", "continent" => asia},
  {"name" => "Pakistan", "continent" => asia},
  {"name" => "Palau", "continent" => oceania},
  {"name" => "Panama", "continent" => north_america},
  {"name" => "Papua New Guinea", "continent" => oceania},
  {"name" => "Paraguay", "continent" => south_america},
  {"name" => "Peru", "continent" => south_america},
  {"name" => "Philippines", "continent" => asia},
  {"name" => "Pitcairn", "continent" => oceania},
  {"name" => "Poland", "continent" => europe},
  {"name" => "Portugal", "continent" => europe},
  {"name" => "Puerto Rico", "continent" => north_america},
  {"name" => "Qatar", "continent" => asia},
  {"name" => "South Korea(Republic of Korea) ", "continent" => asia},
  {"name" => "Republic of Moldova", "continent" => europe},
  {"name" => "Réunion", "continent" => africa},
  {"name" => "Romania", "continent" => europe},
  {"name" => "Russian Federation", "continent" => europe},
  {"name" => "Rwanda", "continent" => africa},
  {"name" => "Saint Barthélemy", "continent" => north_america},
  {"name" => "Saint Helena", "continent" => africa},
  {"name" => "Saint Kitts and Nevis", "continent" => north_america},
  {"name" => "Saint Lucia", "continent" => north_america},
  {"name" => "Saint Martin (French Part)", "continent" => north_america},
  {"name" => "Saint Pierre and Miquelon", "continent" => north_america},
  {"name" => "Saint Vincent and the Grenadines", "continent" => north_america},
  {"name" => "Samoa", "continent" => oceania},
  {"name" => "San Marino", "continent" => europe},
  {"name" => "Sao Tome and Principe", "continent" => africa},
  {"name" => "Sark", "continent" => europe},
  {"name" => "Saudi Arabia", "continent" => asia},
  {"name" => "Senegal", "continent" => africa},
  {"name" => "Serbia", "continent" => europe},
  {"name" => "Seychelles", "continent" => africa},
  {"name" => "Sierra Leone", "continent" => africa},
  {"name" => "Singapore", "continent" => asia},
  {"name" => "Sint Maarten (Dutch part)", "continent" => north_america},
  {"name" => "Slovakia", "continent" => europe},
  {"name" => "Slovenia", "continent" => europe},
  {"name" => "Solomon Islands", "continent" => oceania},
  {"name" => "Somalia", "continent" => africa},
  {"name" => "South Africa", "continent" => africa},
  {"name" => "South Georgia and the South Sandwich Islands", "continent" => south_america},
  {"name" => "South Sudan", "continent" => africa},
  {"name" => "Spain", "continent" => europe},
  {"name" => "Sri Lanka", "continent" => asia},
  {"name" => "State of Palestine", "continent" => asia},
  {"name" => "Sudan", "continent" => africa},
  {"name" => "Suricountry", "continent" => south_america},
  {"name" => "Svalbard and Jan Mayen Islands", "continent" => europe},
  {"name" => "Sweden", "continent" => europe},
  {"name" => "Switzerland", "continent" => europe},
  {"name" => "Syrian Arab Republic", "continent" => asia},
  {"name" => "Tajikistan", "continent" => asia},
  {"name" => "Thailand", "continent" => asia},
  {"name" => "Timor-Leste", "continent" => asia},
  {"name" => "Togo", "continent" => africa},
  {"name" => "Tokelau", "continent" => oceania},
  {"name" => "Tonga", "continent" => oceania},
  {"name" => "Trinidad and Tobago", "continent" => north_america},
  {"name" => "Tunisia", "continent" => africa},
  {"name" => "Turkey", "continent" => asia},
  {"name" => "Turkmenistan", "continent" => asia},
  {"name" => "Turks and Caicos Islands", "continent" => north_america},
  {"name" => "Tuvalu", "continent" => oceania},
  {"name" => "Uganda", "continent" => africa},
  {"name" => "Ukraine", "continent" => europe},
  {"name" => "United Arab Emirates", "continent" => asia},
  {"name" => "United Kingdom of Great Britain and Northern Ireland", "continent" => europe},
  {"name" => "United Republic of Tanzania", "continent" => africa},
  {"name" => "United States Minor Outlying Islands", "continent" => oceania},
  {"name" => "United States of America", "continent" => north_america},
  {"name" => "United States Virgin Islands", "continent" => north_america},
  {"name" => "Uruguay", "continent" => south_america},
  {"name" => "Uzbekistan", "continent" => asia},
  {"name" => "Vanuatu", "continent" => oceania},
  {"name" => "Venezuela (Bolivarian Republic of)", "continent" => south_america},
  {"name" => "Vietnam", "continent" => asia},
  {"name" => "Wallis and Futuna Islands", "continent" => oceania},
  {"name" => "Western Sahara", "continent" => africa},
  {"name" => "Yemen", "continent" => asia},
  {"name" => "Zambia", "continent" => africa},
  {"name" => "Zimbabwe", "continent" => africa}
]

locations = []
for country in countries
  continent_id = country["continent"].id
  country = Country.new( country )
  country.save()
  location = ({"country_id" => country.id, "continent_id" => continent_id })
  locations.push( location )
end

for location in locations
  location = Location.new( location )
  location.save()
end
